# Generated by Django 4.0.8 on 2022-10-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_num',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
