# Generated by Django 4.0.8 on 2022-10-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dept',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
