# Generated by Django 4.0.8 on 2022-10-10 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.profile')),
            ],
        ),
    ]
