# Generated by Django 4.0.8 on 2022-10-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='City',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='info',
            name='Country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='info',
            name='street',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
