# Generated by Django 4.0.8 on 2022-10-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_alter_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
