# Generated by Django 4.0.8 on 2022-10-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='id_c',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='id_p',
        ),
    ]
