# Generated by Django 4.0.8 on 2022-10-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_rename_id_category_id_c_rename_id_product_id_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id_c',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_p',
            new_name='id',
        ),
    ]
