# Generated by Django 4.0.8 on 2022-10-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Category_id',
        ),
    ]
