# Generated by Django 4.0.8 on 2022-10-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_remove_product_category_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
