# Generated by Django 4.0.8 on 2022-10-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
