# Generated by Django 4.0.8 on 2022-10-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_alter_pro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
