# Generated by Django 4.0.8 on 2022-10-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_pro_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='Sku',
            field=models.CharField(default=0, max_length=30, unique=True),
        ),
    ]
