# Generated by Django 4.0.8 on 2022-10-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0028_pro_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pro',
            name='image',
            field=models.ImageField(default=0, upload_to='img'),
        ),
    ]
