# Generated by Django 4.0.8 on 2022-10-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0029_pro_price_alter_pro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
