# Generated by Django 4.0.8 on 2022-10-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0030_alter_pro_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro',
            name='price',
        ),
    ]
