# Generated by Django 4.0.8 on 2022-10-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0031_remove_pro_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
