# Generated by Django 4.0.8 on 2022-10-11 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0032_pro_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='category_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mysite.category'),
        ),
    ]
