# Generated by Django 4.0.8 on 2022-10-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0033_pro_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro',
            name='category_id',
        ),
    ]
