# Generated by Django 4.0.8 on 2022-10-11 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0036_remove_pro_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='category_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='mysite.category'),
        ),
    ]
