# Generated by Django 4.0.8 on 2022-10-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0038_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
