# Generated by Django 4.0.8 on 2022-10-19 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0039_delete_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.category'),
        ),
    ]
