# Generated by Django 4.0.8 on 2022-10-19 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0040_alter_pro_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='category_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mysite.category'),
        ),
    ]
