# Generated by Django 4.0.8 on 2022-10-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0041_alter_pro_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro',
            name='category_id',
        ),
        migrations.AddField(
            model_name='pro',
            name='category_id_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.category'),
            preserve_default=False,
        ),
    ]
