# Generated by Django 4.0.8 on 2022-10-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0042_remove_pro_category_id_pro_category_id_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pro',
            old_name='category_id_id',
            new_name='category_id',
        ),
    ]
