# Generated by Django 4.0.8 on 2022-10-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0047_rename_category_id_pro_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pro',
            old_name='category',
            new_name='category_id',
        ),
    ]
