# Generated by Django 4.0.8 on 2022-10-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0049_rename_category_id_pro_category_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pro',
        ),
    ]
