# Generated by Django 4.0.8 on 2022-10-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0051_pro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pro',
            old_name='name1',
            new_name='product_name',
        ),
    ]
